// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/ryvasa/go-restaurant/internal/delivery/http/handler"
	"github.com/ryvasa/go-restaurant/internal/repository"
	"github.com/ryvasa/go-restaurant/internal/usecase"
	"github.com/ryvasa/go-restaurant/pkg/config"
	"github.com/ryvasa/go-restaurant/pkg/database"
)

// Injectors from wire.go:

// InitializeHandlers initializes Handlers with dependencies
func InitializeHandlers() (*handler.Handlers, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	string2 := database.ProvideDSN(configConfig)
	db, err := database.NewMySQLConnection(string2)
	if err != nil {
		return nil, err
	}
	menuRepository := repository.NewMenuRepository(db)
	menuUsecase := usecase.NewMenuUsecase(menuRepository)
	menuHandlerImpl := handler.NewMenuHandler(menuUsecase)
	userRepository := repository.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userHandlerImpl := handler.NewUserHandler(userUsecase)
	handlers := handler.NewHandlers(menuHandlerImpl, userHandlerImpl)
	return handlers, nil
}

// wire.go:

var menuSet = wire.NewSet(repository.NewMenuRepository, usecase.NewMenuUsecase, handler.NewMenuHandler)

var userSet = wire.NewSet(repository.NewUserRepository, usecase.NewUserUsecase, handler.NewUserHandler)
