// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/ryvasa/go-restaurant/internal/delivery/http/handler"
	"github.com/ryvasa/go-restaurant/internal/repository"
	"github.com/ryvasa/go-restaurant/internal/usecase"
)

// Injectors from wire.go:

// InitializeUserHandler initializes UserHandler with dependencies
func InitializeMenuHandler(db *sql.DB) *handler.MenuHandler {
	menuRepository := repository.NewMenuRepository(db)
	menuUsecase := usecase.NewMenuUsecase(menuRepository)
	menuHandler := handler.NewMenuHandler(menuUsecase)
	return menuHandler
}
